apiVersion: apps/v1
kind: Deployment
metadata:
  name: balances-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efood
      service: balances
  template:
    metadata:
      labels:
        app: efood
        service: balances
        sidecar.istio.io/inject: "true"
        version: "1"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - name: balances
        image: ghcr.io/wofood/efood_balances
        # resources:
        #   requests:
        #     memory: "500Mi"
        #     cpu: "250m"
        ports:
          - name: balances
            protocol: TCP
            containerPort: 3000
        envFrom:
          - configMapRef:
              name: efood-config
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
