apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: balances-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: balances-depl
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
